### ISSUE TITLE
British English en-UK?

### ISSUE THREAD

**Issue by Fania** [Microsoft/vscode-spell-check#29]
Can you add support for British English?
That would be jolly good!

**Comment by theWhiteFox** [comment]
Well now Seán, if you're going to do British English (queen's language / proper English) can you do Spanglish?

**Comment by Tyriar** [comment]
:+1: for en-AU as well. It looks like very basic checking currently because it doesn't flag on either color or colour. This means a lot of typos won't be caught.

This is not possible currently due to limitations with the spell check module https://www.npmjs.com/package/teacher

Atom uses/created https://www.npmjs.com/package/spellchecker which looks like it defers spellchecking to the OS which is far more preferable and would probably remove the need to change the language at all.

ping @seanmcbreen

**Comment by seanmcbreen** [comment]
Hi,

Unfortunately the package above uses a native module - this is currently not supported in VS Code.  Additionally we would loose Grammar and other checks if we moved from `teacher`.

I'm from New Zealand and feel the US English pain but for now there is no good solution I can think of.

Sorry :cry: 
Sean
