### ISSUE TITLE
Spell check comments in code

### ISSUE THREAD

**Issue by scottwio** [Microsoft/vscode-spell-check#4]
It would be really nice if this plugin could check spelling within comments in any programming language expanding it's usage outside of markdown.

**Comment by Oriphiel** [comment]
Error:
No handler found for the command: 'Spell.changeLanguage'

**Comment by seanmcbreen** [comment]
@Oriphiel that sounds like an issue in your version sorry about that have you got `0.3.0`?  I'm pretty sure this issue is fixed if not LMK.

@scottwio I have a very [arbitrary language filer in the code](https://github.com/Microsoft/vscode-spell-check/blob/master/extension.ts#L61) you could try it without it - but the key issue is to know how comment blocks are delineated in any language - this was the thing I avoided to date.  I know we have some token information for this so it's possible but I did not have time yet to implement.

**Comment by IntelOrca** [comment]
Could a configuration option be added so the user can choose additional file types to spell check?
For example:
```json
{
    "languageIds": [
        "text"
        "markdown",
        "reStructuredText"
    ]
}
```

Types like *.txt and *.rst aren't code so they should be supported as well.

**Comment by seanmcbreen** [comment]
@IntelOrca added in 0.4.0 :)
@Oriphiel also improved error checking and added an error message if the language ID is not in the list
@scottwio you can now add any language - but it will get messy quickly where a lot of keywords exist

**Comment by IntelOrca** [comment]
@seanmcbreen thanks :+1:

**Comment by Oriphiel** [comment]
@seanmcbreen ty, works fine now :)

**Comment by rsgoodwin** [comment]
I added "reStructuredText" in my spell.json file (from IntelOrca) and I could not get it to spell check .rst files.  In fact,  the only files it seems spell check are .md.   I tested with a .txt file and I could not get it to spell check there either.  Is there another configuration to indicate what file extensions can be spell checked?  I may be missing the obvious somewhere. 

Thanks!
