### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-spell-check#46]
- VSCode Version: 1.4.0-insiders
- OS Version: Linux

Steps to Reproduce:

1. Install Markdown spelling extension
2. F8 thru a markdown file
![image](https://cloud.githubusercontent.com/assets/6461412/17014955/b73e9188-4f27-11e6-9ef6-8385a377f5ed.png)

The error message should be human readable. I'd change it to a sentense and also remove the suggestions.

**Comment by seanmcbreen** [comment]
The issue here is that the same message is used for the hover and to generate the suggestions [ a little lazy I know the suggestions are a split by `,` on the hover text].  And the same format is used for all error types e.g. a complex expression, `i` is not capitalized.  So the format is

`error type` [`error`] - suggest [`suggestion1`, `sugestion2`, ...]

I could not come up with a better general purpose scheme :(

LMK if you have a brain wave.
