### ISSUE TITLE
Extension does not seem to work for long files

### ISSUE THREAD

**Issue by gauravbaruah** [Microsoft/vscode-spell-check#47]
Hi, 

This spell check extension is simply superb and was a great help to me for writing in Latex.

I observed that spelling/grammar errors were not shown for .tex files that were longer than 600 or 700 lines. The spelling/grammar errors were shown for files smaller than 600 lines in length.

**Comment by seanmcbreen** [comment]
Hum - one issue is that the entire file is checked so it can take a while for a longer file.  We use it on some pretty big ones that said if you are happy to share the file I could look into it.

**Comment by skariel** [comment]
can confirm. I'm sharing my file for which it doesn't work
[KN16_v3_adi.tex.zip](https://github.com/Microsoft/vscode-spell-check/files/436545/KN16_v3_adi.tex.zip)

**Comment by seanmcbreen** [comment]
Thanks for passing on that file it helped a lot.  I was able to get the checker to work.  The core issue is that once working there will be a lot of errors.  This is mainly due to the fact that the checker does not understand LaTeX very well.   So it's not so much document size but the number of reporting issues.

I try to work around that a little below with a feature to remove parts of the doc before the checking is done.

## pre-reqs:

1. Install the LaTeX Colorizer extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.latex
2. Ensure you have added LaTeX into the supported file types in `spell.json` i.e.

 ```json
  "languageIDs": [
    "markdown",
    "text",
    "todo",
    "latex"
  ],
 ```
3. Restart VS Code with `F1` and then `Reload Window`

## Filter LaTeX & Only Enable when Required

Then you need to add a set of regular expressions to the `spell.json` file to reduce the errors from ~1,000 to ~250.  I think the best way to use the checker with a document like this will be to enable it only when you are proofing by clicking on the status bar. 

![image](https://cloud.githubusercontent.com/assets/1051190/18022412/88f454fa-6ba3-11e6-8c74-63b4b0560f99.png)

In live mode reported errors will come back slower than you type which will be pretty confusing.

>**Tip:** In the `spell.json` file they need to be escaped out with each `\` being replaces by four `\\\\`.

```json
  "ignoreRegExp": [
    "/(\\\\\\\\setlength{.*}|\\\\\\\\usepackage{.*}|\\\\\\\\text(bf|sl|tt|it|sc){.*}|\\\\\\\\newcommand{.*}|\\\\\\\\item|\\\\\\\\item\\\\[.*\\\\]|\\\\\\\\hline)/gm",
    "/(\\\\\\\\section{.*}|\\\\\\\\subsection{.*}|\\\\\\\\begin{.*}|\\\\\\\\end{.*}|\\\\\\\\sitep{.*}|\\\\\\\\label{.*}|\\\\\\\\ref{.*}|\\\\\\\\includegraphics\\\\[.*\\\\]{.*}|\\\\\\\\citep{.*}|\\\\\\\\epsfig{.*})/gm",
    "/(\\\\\\\\def\\\\\\\\.*{.*})/gm",
    "/(\\\\$.*?\\\\$)/gm"
  ]
```

##  Checked Document

You may have to make an edit and the round trip could take 5-10 secs.  But there is a capture of the results...

![image](https://cloud.githubusercontent.com/assets/1051190/18022345/d21c3a68-6ba2-11e6-8c8a-d10d701d2fcd.png)


# Improving RegExps

These are pretty hacky RegExps and you could improve them.  A great place to check the impact of RegExps is www.regexp101.com

I'd love to know if this helped.  It's not ideal sorry but should be workable.

Sean

**Comment by skariel** [comment]
Thanks, @seanmcbreen now I have a problem that replacing words disables the word wrap mode... should I open a new issue?

**Comment by skariel** [comment]
just opened a new issue, see #50

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
