### ISSUE TITLE
Can we have a F1 option to manually enable/disable the spell checker?

### ISSUE THREAD

**Issue by J-Siu** [Microsoft/vscode-spell-check#53]
Can we have a F1 option to manually enable/disable the spell checker?

I mostly only use spell checker when I am writing the Readme.md. There is really no point to enable the spell checker when I am writing code.

**Comment by rozzzly** [comment]
I love that. And maybe an additional option to disable for x minutes. Right now I have this extension disabled because I get frustrated when it doesn't remember words I set it to ignore (mainly with compound words/with punctuation and, or hyphens (`-`).  I wish I could have it setup to where that keybinding/command turns off the spell checker for say 30m, then have it auto reenable. Otherwise I turn it off and write misspelled for a few days before I remember to town it back on.

**Comment by seanmcbreen** [comment]
Quick clarifying question is the status bar option not enough i.e. if you click on it the checker will be disabled.

![image](https://cloud.githubusercontent.com/assets/1051190/18812507/0a9b86f0-828c-11e6-82f1-904e56544dc1.png)

**Comment by J-Siu** [comment]
I just installed it again, and YES, the status bar option is PERFECT!!! Thank you!!!!

**Comment by seanmcbreen** [comment]
Rock on @rozzzly is this enough for you - if so I will close.

**Comment by seanmcbreen** [comment]
Also if you do like this help me out and rate it in the marketplace.

**Comment by rozzzly** [comment]
@seanmcbreen awesome! I still want the timer thing, but that's not very difficult to add, I'll PR it myself when I have a little time.

**Comment by seanmcbreen** [comment]
Perfect for now I'll close this issue.
