### ISSUE TITLE
Global spell.json

### ISSUE THREAD

**Issue by IntelOrca** [Microsoft/vscode-spell-check#7]
Feature request to have a spell.json `~/.vscode.json` which then has individual properties overridden by the workspace spell.json `./.vscode/spell.json`.

I am not sure what the convention of global extension settings is for vscode (so it can be done the way it is supposed to be done if the above is not correct), basically just a way of having global fall-back settings so they work across different projects.

**Comment by csinco** [comment]
I would also suggest having a way to configure this outside the .vscode folder.  I'd like to have spell check handy for the random files I open that don't necessarily have a single folder context.

**Comment by seanmcbreen** [comment]
Dude,

Hope all is well - I like this idea.  So when I come back (which is soon 22nd Feb) I'll work out how to do it.  Hope all is well!

Sean

**Comment by OneOfOne** [comment]
Maybe allow us to set the options in the global `settings.json`?

Most plugins allow that, for example the go plugin.

Also any chance to allow checking the comments? (specifically in Go)

**Comment by daviscale** [comment]
I was surprised that the extension was looking for `spell.json` [like this](https://github.com/Microsoft/vscode-spell-check/blob/master/extension.ts#L29):

```
let CONFIGFILE = workspace.rootPath + "/.vscode/spell.json";
```

I thought it would look for `spell.json` in `~/.vscode.json`. I don't need a different `spell.json` for each workspace I use, so I temporarily resolved this by placing this in extension.js:

```javascript
var CONFIGFILE = "~/.vscode/spell.json";
```

I think that the two alternatives mentioned so far (having a global `spell.json` and setting options in `settings.json`) would be an improvement over the current approach.

**Comment by rozzzly** [comment]
@daviscale not only that, but when I first installed the extension, I thought it was broken/super limited because I wasn't getting any checking in `.ts`/`.js` files. I only noticed that `languageIDs` was configurable when I stumbled upon https://github.com/Microsoft/vscode-docs/blob/master/.vscode/spell.json

I suppose this would warrant its own feature request/PR to at the very least, state in the _"LanguageID: javascript not suported for spell checking."_ message that languageID was configurable in the first place. :laughing: 

---

#### side note: 
in that error message...
> LanguageID: javascript not _**suported**_ for spell checking.

awhhh the irony its killing me :if js was one of the defaults, the developer would have caught that ;P

I'll submit a PR for the updated error later today, and see what the maintainers think about having some type of prompt to "customize spell checker" which creates the default `spell.json` file. That way atleast it'll be obvious for stupid people like me :stuck_out_tongue_winking_eye:

**Comment by Fania** [comment]
I'd like global settings too.
But I also agree with @csinco to have it work with individual random files.

**Comment by asifm** [comment]
It's only by reading this thread that I came to understand the spell.json file is located in the workspace .vscode folder. I was looking in the global .vscode folder. The readme file can be more explicit about this.

**Comment by erichiller** [comment]
Even better would be if the configuration were set in the "User Configuration" right from the menu along with other plugins such as Golang ,etc...

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
